name: CI/CD Backend Despachos

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build imagen Docker
        run: |
          docker build -t despacho-backend .

      - name: Tag y Push a ECR
        run: |
          docker tag despacho-backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
          docker tag despacho-backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:${{ github.sha }}

      - name: Deploy en EC2 Backend via SSM
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPO_URL: ${{ secrets.ECR_REPO_URL_BACKEND }}
          INSTANCE_ID: ${{ secrets.EC2_BACKEND_INSTANCE_ID }}
          DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          COMMAND="aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY} && docker pull ${ECR_REPO_URL}:latest && docker stop despacho-backend || true && docker rm despacho-backend || true && docker run -d --name despacho-backend --network=host --restart unless-stopped -e DB_ENDPOINT=${DB_ENDPOINT} -e DB_PORT=3306 -e DB_NAME=${DB_NAME} -e DB_USERNAME=${DB_USERNAME} -e DB_PASSWORD=${DB_PASSWORD} ${ECR_REPO_URL}:latest"
          aws ssm send-command \
            --instance-ids "${INSTANCE_ID}" \
            --document-name "AWS-RunShellScript" \
            --parameters commands=["${COMMAND}"] \
            --region "${AWS_REGION}"
